# Generated by Django 2.2.2 on 2019-06-09 14:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountMturk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('key_access', models.CharField(max_length=200)),
                ('key_secret', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Mturk Account',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('use_sandbox', models.BooleanField(default=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('test', models.TextField(blank=True, null=True)),
                ('answer_key', models.TextField(blank=True, null=True)),
                ('keywords', models.ManyToManyField(to='mturk_manager.Keyword')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_frame', models.IntegerField()),
                ('content', models.TextField()),
                ('json_dict_parameters', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_worker', models.CharField(max_length=200, unique=True)),
                ('global_block', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id_worker'],
            },
        ),
        migrations.CreateModel(
            name='SettingsBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(null=True)),
                ('reward', models.IntegerField(default=0)),
                ('count_assignments', models.IntegerField(default=1)),
                ('count_assignments_max_per_worker', models.IntegerField(blank=True, null=True)),
                ('lifetime', models.IntegerField(default=604800)),
                ('duration', models.IntegerField(default=3600)),
                ('amount_budget_max', models.IntegerField(blank=True, null=True)),
                ('keywords', models.ManyToManyField(to='mturk_manager.Keyword')),
                ('message_reject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mturk_manager.MessageReject')),
                ('qualifications', models.ManyToManyField(to='mturk_manager.Qualification')),
                ('template_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mturk_manager.TemplateWorker')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('datetime_visited', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('account_mturk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mturk_manager.AccountMturk')),
                ('blocked_workers', models.ManyToManyField(to='mturk_manager.Worker')),
                ('settings_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mturk_manager.SettingsBatch')),
            ],
        ),
        migrations.CreateModel(
            name='HIT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hit', models.CharField(max_length=200, unique=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_expiration', models.DateTimeField(db_index=True)),
                ('status', models.IntegerField(choices=[(1, 'Reviewed'), (2, 'NotReviewed')])),
                ('count_assignments_additional', models.IntegerField(default=0)),
                ('count_assignments_dead', models.IntegerField(default=0)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mturk_manager.Batch')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mturk_manager.Project'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_assignment', models.CharField(max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Approved'), (2, 'Pending'), (3, 'Submitted'), (4, 'Rejected')])),
                ('datetime_created', models.DateTimeField()),
                ('datetime_submit', models.DateTimeField(blank=True, null=True)),
                ('datetime_accept', models.DateTimeField(blank=True, null=True)),
                ('answer', models.TextField()),
                ('hit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mturk_manager.HIT')),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mturk_manager.Worker')),
            ],
        ),
    ]
