# Generated by Django 2.2.2 on 2019-06-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mturk_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templateworker',
            old_name='json_dict_parameters',
            new_name='json_parameters',
        ),
    ]
